In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/data_raw/StudentsPerformance.csv')

In [19]:
 #Drop rows where the value in 'test_preparation_course' column is None
df = df[df['test_preparation_course'] != 'none']
df.reset_index(drop=True, inplace=True)

In [20]:
df.head(10)

,gender,race_or_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group C,some college,standard,completed,69,90,88
1,female,group B,some college,standard,completed,88,95,92
2,male,group D,high school,free/reduced,completed,64,64,67
3,male,group A,some college,standard,completed,78,72,70
4,male,group C,master's degree,free/reduced,completed,46,42,46
5,female,group B,some college,free/reduced,completed,65,75,70
6,male,group D,bachelor's degree,free/reduced,completed,74,71,80
7,male,group E,associate's degree,standard,completed,81,81,79
8,female,group D,associate's degree,free/reduced,completed,75,90,88
9,male,group B,some college,free/reduced,completed,59,65,66

In [21]:
print("\nChecking for missing values:")
print(df.isnull().sum())

Checking for missing values:
gender                         0
race_or_ethnicity              0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [22]:
df.columns = df.columns.str.strip()

In [23]:
# Remove duplicates (if any)
df.drop_duplicates(inplace=True)

In [24]:
df.rename(columns = {'race/ethnicity':'race_or_ethnicity',
                     'parental level of education':'parental_level_of_education',
    'test preparation course':'test_preparation_course',
                       'math score':'math_score',
                       'reading score':'reading_score',
                        'writing score':'writing_score'}, inplace = True)

In [25]:
df.to_csv('/content/data_clean/StudentsPerformance.csv')